name: Check Style

on:
  workflow_dispatch:

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 22
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew spotlessCheck
